---
title: "SORTIE Carbon Extension Note"
author: "Leah Walker"
date: "2022-08-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

Load libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ls <- c("tidyverse", "data.table") # Data Management and Manipulation (removed plyr - might need to add back)
ls <- append(ls, c("rsortie")) # sortie
ls <- append(ls, c("lme4", "lmerTest", "Rmisc")) # analysis
ls <- append(ls, c("ggplot2")) # model interpretation/visualization

# Install if needed -- then load. 
new.packages <- ls[!(ls %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
lapply(ls, library, character.only = TRUE)  # load the required packages
rm(ls, new.packages)

```



1. Set parameters
- set pathways
```{r}
#Set pathways
path_outputs <- "./Outputs/"

```

- run makeFiles
- run rsortie
- clean field data
- calculate carbon
- calculate field carbon
- calculate field carbon by species

```{r}
#I'm assuming we only need these scripts if you want to run all the calculations?
BA.function <- function(DBH) {pi*(DBH/200)^2}

source("./R/clean_summit_lake_data.R")
source("./R/calc_field_BA.R")
source("../Carbon/CarbonFunctions.R")
source("../Carbon/AllometryFunctions.R")
source("./R/calc_field_C.R")

###################
### Summit Lake ###
###################



##################
### Date Creek ###
##################



```



2. Read in data

```{r}
###################
### Summit Lake ###
###################

### Field ###
# LIVE
SL_field_L_C <- read.csv("./Inputs/Data/SummitLake_C_field_L.csv") # SL = Summit Lake, L = living, C = carbon

# Live - Hybrid Spruce (Sx)
SL_field_L_C_Sx <- read.csv("./Inputs/Data/SummitLake_C_field_L_Sx.csv")

# Live - Subalpine fir (Bl)
SL_field_L_C_Bl <- read.csv("./Inputs/Data/SummitLake_C_field_L_Bl.csv")



# DEAD
SL_field_D_C <- read.csv("./Inputs/Data/SummitLake_C_field_D.csv") # D = dead



### Sortie ###

#LIVE
SL_L_C <- read.csv("./Inputs/Data/SummitLake_C_0506_L.csv")
# This data frame will be used below to calculate carbon per species

SL_L_C_u <- SL_L_C %>% # u = unit (this data frame is summarized to the unit level)
  dplyr::select(unit, timestep, C_unit, treatment)

SL_L_C_u <- as.data.table(unique(SL_L_C_u))



# DEAD
SL_D_C <- read.csv("./Inputs/Data/SummitLake_C_0506_D.csv")

SL_D_C_u <- SL_D_C %>%
  dplyr::select(unit, timestep, C_unit, treatment)

SL_D_C_u <- as.data.table(unique(SL_D_C_u))



##################
### Date Creek ###
##################

### Field ###
# LIVE
DC_field_L_C <- read.csv("./Inputs/Data/DateCreek_C_field_L.csv") # DC = Date Creek, L = living, C = carbon

# Live - Western red cedar (Cw)
DC_field_L_C_Cw <- read.csv("./Inputs/Data/DateCreek_C_field_L_Cw.csv.csv")

# Live - Western hemlock (Hw)
DC_field_L_C_Hw <- read.csv("./Inputs/Data/DateCreek_C_field_L_Hw.csv")



# DEAD
DC_field_D_C <- read.csv( "./Inputs/Data/DateCreek_C_field_D.csv")



### Sortie ###

# LIVE
DC_L_C <- read.csv("./Inputs/Data/DateCreek_C_L.csv") # DC = Date Creek, L = living, C = carbon
# This data frame will be used below to calculate carbon per species

DC_L_C_p <- DC_L_C %>% # p = plot (this data frame is summarized to the plot level)
  dplyr::select(timestep, Unit, PlotNumber, C_plot, Treatment) 

DC_L_C_p <- unique(DC_L_C_p)

DC_L_C_p <- DC_L_C_p %>% 
  dplyr::group_by(timestep, Unit) %>% 
  dplyr::mutate(C_unit = sum(C_plot, na.rm = TRUE)/count)

DC_L_C_u <- DC_L_C_p %>% # u = unit
  dplyr::select(timestep, Unit, C_unit, Treatment) 

DC_L_C_u <- as.data.table(unique(DC_L_C_u))



# DEAD
DC_D_C <- read.csv("./Inputs/Data/DateCreek_C_D.csv")

DC_D_C_p <- DC_D_C %>% # p = plot (this data frame is summarized to the plot level)
  dplyr::select(timestep, Unit, PlotNumber, C_plot, Treatment) 

DC_D_C_p <- unique(DC_D_C_p)

DC_D_C_p <- DC_D_C_p %>% 
  dplyr::group_by(timestep, Unit) %>% 
  dplyr::mutate(C_unit = sum(C_plot, na.rm = TRUE)/count)

DC_D_C_u <- DC_D_C_p %>% # u = unit
  dplyr::select(timestep, Unit, C_unit, Treatment) 

DC_D_C_u <- as.data.table(unique(DC_D_C_u))

```



3. Live standing carbon
```{r}
###################
### Summit Lake ###
###################

### RSS and RMSE ###

# Compare final year of simulation C to final year of field data C - LIVE ONLY
final_SL_L_C_u <- as.data.table(subset(SL_L_C_u, timestep == 27))

final_SL_field_L_C <- subset(SL_field_L_C, timestep == 27)

final_SL_L_C_u <- merge(final_SL_L_C_u, final_SL_field_L_C, by = c("unit", "treatment", "timestep"))
names(final_SL_L_C_u)[names(final_SL_L_C_u) == "C_unit.x"] <- "C_unit"
names(final_SL_L_C_u)[names(final_SL_L_C_u) == "C_unit.y"] <- "field_C"

SL_rss <- with(final_SL_L_C_u, sum((C_unit - field_C)^2))
SL_rmse <- with(final_SL_L_C_u, sqrt(mean((C_unit - field_C)^2)))



### Linear and mixed effects models ###

# Data manipulation
SL_L_C_u_mod <- subset(SL_L_C_u, timestep == 0 | timestep ==  2 | timestep == 5 | timestep == 17 | timestep == 27)

SL_L_C_u_mod <- merge(SL_L_C_u_mod, SL_field_L_C, by = c("unit", "treatment", "timestep")) # okay that this data frame has 85 observations instead of 93 - the missing observations are because units 16-19 were not measured in years 2 and 5 

names(SL_L_C_u_mod)[names(SL_L_C_u_mod) == "C_unit.x"] <- "sortie"
names(SL_L_C_u_mod)[names(SL_L_C_u_mod) == "C_unit.y"] <- "field"

SL_L_C_u_mod2 <- melt(SL_L_C_u_mod, id.vars = c("unit", "treatment", "timestep"), measure.vars = c("sortie", "field")) # Should be 170 observations
names(SL_L_C_u_mod2)[names(SL_L_C_u_mod2) == "variable"] <- "DataSource"
names(SL_L_C_u_mod2)[names(SL_L_C_u_mod2) == "value"] <- "C_unit"

SL_L_C_u_mod2 <- SL_L_C_u_mod2 %>%
  mutate(unit = as.character(unit))

# Basic linear model
SL_L_C_lm <- lm(C_unit ~ DataSource, SL_L_C_u_mod2) # does not force the intercept through zero, tells us the difference between the two means
summary(SL_L_C_lm)

# Mixed effects models
SL_L_C_lmer <- lmer(C_unit ~ DataSource * treatment + (1|unit/timestep), SL_L_C_u_mod2)
summary(SL_L_C_lmer)



# Plot all timesteps at once
png("./Figures/SL_alltime_L_C.png", width=700, height=500, units="px", pointsize=23, antialias="default")

ggplot(SL_L_C_u_mod, aes(x = field, y = sortie, shape = treatment, color = treatment)) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), 
        axis.text = element_text(size = 15), 
        axis.title = element_text(size = 18), 
        legend.title = element_text(size = 18), 
        legend.text = element_text(size = 17)) +
  geom_point(aes(colour = factor(treatment), shape = factor(treatment)), size = 2) +
  geom_abline() +
  scale_x_continuous(breaks = seq(0, 120, by = 10), limits = c(0, 120)) +
  scale_y_continuous(breaks = seq(0, 120, by = 10), limits = c(0, 120)) +
  labs(x = "Observed Carbon (Mg/ha)", y = "Predicted Carbon (Mg/ha)", col = "Treatment", shape = "Treatment") +
  scale_shape_manual(values = c(16, 15, 17),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention"))

dev.off()



# Plot carbon over time by treatment
SL_field_L_C_T <- summarySE(SL_field_L_C,
                      measurevar="C_unit",
                      groupvars=c("treatment", "timestep"))

SL_field_L_C_T$N <- NULL

SL_L_C_u_T <- summarySE(SL_L_C_u,
                      measurevar="C_unit",
                      groupvars=c("treatment", "timestep"))

SL_L_C_u_T$N <- NULL

png("./Figures/SL_L_C_T.png", width=1600, height=800, units="px",
    pointsize=23, antialias="default")

ggplot(NULL, aes(x = timestep,  y = C_unit, fill = treatment, group = treatment)) + 
  geom_line(data = SL_L_C_u_T, aes(col = treatment), size = 1.2) + 
  theme(axis.line = element_line(colour = "black"), 
        panel.background = element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 25),
        text = element_text(size = 28),
        axis.text = element_text(size = 23),
        axis.text.x = element_text(vjust = -1),
        axis.text.y = element_text(hjust = 0.5),
        axis.ticks.length = unit(7, "pt"),
        axis.title.x = element_text(margin = margin(t = 14,  r = 0, b = 1, l = 0), face = "bold"),
        axis.title.y = element_text(face = "bold")) +
  scale_x_continuous(breaks = seq(0, 28, by = 2), expand = expansion(mult = c(0, 0.05))) +
  scale_y_continuous(breaks = seq(0, 120, by = 20), expand = c(0,0), limits = c(0,120)) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention")) +
  scale_fill_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention")) +
  coord_cartesian(ylim = c(0, 120)) +
  labs(x = "Years post treatment", y = "Carbon (Mg/ha)", col = "Treatment", fill = "Treatment", shape = "Treatment") +
  geom_ribbon(data = SL_L_C_u_T, aes(ymin = C_unit - ci, ymax = C_unit + ci),  alpha=0.1, linetype="dashed",  color="grey") +
  geom_point(data = SL_field_L_C_T, aes(shape = treatment), size = 5 , position = position_dodge(width = 0.5)) +
  scale_shape_manual(values = c(24, 23, 21),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  geom_errorbar(data = SL_field_L_C_T, aes(ymin = C_unit - ci, ymax = C_unit + ci), position = position_dodge(width = 1)) 
  
dev.off()




##################
### Date Creek ###
##################



```



4. Dead standing carbon
```{r}
###################
### Summit Lake ###
###################

# Merge data frame with labels, so all timesteps have a C_unit (to include zeros)

labels.treatment <- unique(subset(SL_D_C_u, select = c("unit", "treatment")))

labels.time <- data.frame(unit = c(rep(3, 28), rep(4, 28), rep(5, 28), rep(6, 28), rep(7, 28), rep(8, 28), rep(9, 28), rep(10, 28), rep(11, 28), rep(12, 28), rep(13, 28), rep(14, 28), rep(15, 28), rep(16, 28), rep(17, 28), rep(18, 28), rep(19, 28), rep(20, 28), rep(24, 28)), timestep = rep(seq(0, 27, by = 1), times = 19))

labels <- merge(labels.treatment, labels.time, by = "unit")

SL_D_C_u <- merge(SL_D_C_u, labels, by = c("unit", "timestep"), all.y = TRUE)

SL_D_C_u$treatment.x <- NULL

names(SL_D_C_u)[names(SL_D_C_u) == "treatment.y"] <- "treatment"

SL_D_C_u <- SL_D_C_u %>%
    dplyr::mutate(C_unit = replace(C_unit, is.na(C_unit), 0))



### RSS and RMSE ###

# Compare final year of simulation C to final year of field data C - DEAD ONLY
final_SL_D_C_u <- as.data.table(subset(SL_D_C_u, timestep == 27))

final_SL_field_D_C <- subset(SL_field_D_C, timestep == 27)

final_SL_D_C_u <- merge(final_SL_D_C_u, final_SL_field_D_C, by = c("unit", "treatment", "timestep"))
names(final_SL_D_C_u)[names(final_SL_D_C_u) == "C_unit.x"] <- "C_unit"
names(final_SL_D_C_u)[names(final_SL_D_C_u) == "C_unit.y"] <- "field_C"

SL_rss <- with(final_SL_D_C_u, sum((C_unit - field_C)^2))
SL_rmse <- with(final_SL_D_C_u, sqrt(mean((C_unit - field_C)^2)))



### Linear and mixed effects models ###

# Data manipulation
SL_D_C_u_mod <- subset(SL_D_C_u, timestep == 0 | timestep ==  2 | timestep == 5 | timestep == 17 | timestep == 27)

SL_D_C_u_mod <- merge(SL_D_C_u_mod, SL_field_D_C, by = c("unit", "treatment", "timestep")) # okay that this data frame has 85 observations instead of 93 - the missing observations are because units 16-19 were not measured in years 2 and 5 
names(SL_D_C_u_mod)[names(SL_D_C_u_mod) == "C_unit.x"] <- "sortie"
names(SL_D_C_u_mod)[names(SL_D_C_u_mod) == "C_unit.y"] <- "field"

SL_D_C_u_mod2 <- melt(SL_D_C_u_mod, id.vars = c("unit", "treatment", "timestep"), measure.vars = c("sortie", "field")) # Should be 170 observations
names(SL_D_C_u_mod2)[names(SL_D_C_u_mod2) == "variable"] <- "DataSource"
names(SL_D_C_u_mod2)[names(SL_D_C_u_mod2) == "value"] <- "C_unit"

SL_D_C_u_mod2 <- SL_D_C_u_mod2 %>%
  mutate(unit = as.character(unit))

# Basic linear model
SL_D_C_lm <- lm(C_unit ~ DataSource, SL_D_C_u_mod2) # does not force the intercept through zero, tells us the difference between the two means
summary(SL_D_C_lm)

# Mixed effects models
SL_D_C_lmer <- lmer(C_unit ~ DataSource * treatment + (1|unit/timestep), SL_D_C_u_mod2)
summary(SL_D_C_lmer)



# Plot all timesteps at once
png("./Figures/SL_alltime_D_C.png", width=700, height=500, units="px", pointsize=23, antialias="default")

ggplot(SL_D_C_u_mod, aes(x = field, y = sortie, shape = treatment, color = treatment)) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), 
        axis.text = element_text(size = 15), 
        axis.title = element_text(size = 18), 
        legend.title = element_text(size = 18), 
        legend.text = element_text(size = 17)) +
  geom_point(aes(colour = factor(treatment), shape = factor(treatment)), size = 2) +
  geom_abline() +
  scale_x_continuous(breaks = seq(0, 35, by = 5), limits = c(0, 35)) +
  scale_y_continuous(breaks = seq(0, 35, by = 5), limits = c(0, 35)) +
  labs(x = "Observed Carbon (Mg/ha)", y = "Predicted Carbon (Mg/ha)", col = "Treatment", shape = "Treatment") +
  scale_shape_manual(values = c(16, 15, 17),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention"))

dev.off()



# Plot carbon over time by treatment
SL_field_D_C_T <- summarySE(SL_field_D_C,
                      measurevar="C_unit",
                      groupvars=c("treatment", "timestep"))

SL_field_D_C_T$N <- NULL

SL_D_C_u_T <- summarySE(SL_D_C_u,
                      measurevar="C_unit",
                      groupvars=c("treatment", "timestep"))

SL_D_C_u_T$N <- NULL

png("./Figures/SL_D_C_T.png", width=1600, height=800, units="px",
    pointsize=23, antialias="default")

ggplot(NULL, aes(x = timestep,  y = C_unit, fill = treatment, group = treatment)) + 
  geom_line(data = SL_D_C_u_T, aes(col = treatment), size = 1.2) + 
  theme(axis.line = element_line(colour = "black"), 
        panel.background = element_blank(), 
        legend.position = "top", 
        legend.text = element_text(size = 25),
        text = element_text(size = 28),
        axis.text = element_text(size = 23),
        axis.text.x = element_text(vjust = -1),
        axis.text.y = element_text(hjust = 0.5),
        axis.ticks.length = unit(7, "pt"),
        axis.title.x = element_text(margin = margin(t = 14,  r = 0, b = 1, l = 0), face = "bold"),
        axis.title.y = element_text(face = "bold")) +
  scale_x_continuous(breaks = seq(0, 28, by = 2), expand = expansion(mult = c(0, 0.05))) +
  scale_y_continuous(breaks = seq(-10, 25, by = 5), expand = c(0,0), limits = c(-10, 25)) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention")) +
  scale_fill_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention")) +
  coord_cartesian(ylim = c(0, 25)) +
  labs(x = "Years post treatment", y = "Carbon (Mg/ha)", col = "Treatment", fill = "Treatment", shape = "Treatment") +
  geom_ribbon(data = SL_D_C_u_T, aes(ymin = C_unit - ci, ymax = C_unit + ci),  alpha=0.1, linetype="dashed",  color="grey") +
  geom_point(data = SL_field_D_C_T, aes(shape = treatment), size = 5 , position = position_dodge(width = 0.5)) +
  scale_shape_manual(values = c(24, 23, 21),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  geom_errorbar(data = SL_field_D_C_T, aes(ymin = C_unit - ci, ymax = C_unit + ci), position = position_dodge(width = 1)) 
  
dev.off()



##################
### Date Creek ###
##################



```



5. Carbon by species (LIVE ONLY)
```{r}
###################
### Summit Lake ###
###################

### Interior spruce ###

# Subset for Spruce
SL_L_C_Sx <- subset(SL_L_C, SL_L_C$Species == "Sx")

# Recalculate C per unit for spruce only
SL_L_C_Sx <- SL_L_C_Sx %>% 
  dplyr::group_by(timestep, unit) %>% 
  dplyr::mutate(C_unit = sum(C_tree, na.rm = TRUE))

# Select desired columns
SL_L_C_Sx_u <- SL_L_C_Sx %>%
  dplyr::select(unit, timestep, C_unit, treatment)

SL_L_C_Sx_u <- as.data.table(unique(SL_L_C_Sx_u))



### RSS and RMSE ###

# Compare final year of simulation C to final year of field data C - LIVE ONLY
final_SL_L_C_Sx_u <- as.data.table(subset(SL_L_C_Sx_u, timestep == 27))

final_SL_field_L_C_Sx <- subset(SL_field_L_C_Sx, timestep == 27)

final_SL_L_C_Sx_u <- merge(final_SL_L_C_Sx_u, final_SL_field_L_C_Sx, by = c("unit", "treatment", "timestep"))
names(final_SL_L_C_Sx_u)[names(final_SL_L_C_Sx_u) == "C_unit.x"] <- "C_unit"
names(final_SL_L_C_Sx_u)[names(final_SL_L_C_Sx_u) == "C_unit.y"] <- "field_C"

SL_Sx_rss <- with(final_SL_L_C_Sx_u, sum((C_unit - field_C)^2))
SL_Sx_rmse <- with(final_SL_L_C_Sx_u, sqrt(mean((C_unit - field_C)^2)))



### Linear and mixed effects models ###

# Data manipulation
SL_L_C_Sx_u_mod <- subset(SL_L_C_Sx_u, timestep == 0 | timestep ==  2 | timestep == 5 | timestep == 17 | timestep == 27)

SL_L_C_Sx_u_mod <- merge(SL_L_C_Sx_u_mod, SL_field_L_C_Sx, by = c("unit", "treatment", "timestep")) # okay that this data frame has 85 observations instead of 93 - the missing observations are because units 16-19 were not measured in years 2 and 5 

names(SL_L_C_Sx_u_mod)[names(SL_L_C_Sx_u_mod) == "C_unit.x"] <- "sortie"
names(SL_L_C_Sx_u_mod)[names(SL_L_C_Sx_u_mod) == "C_unit.y"] <- "field"

SL_L_C_Sx_u_mod2 <- melt(SL_L_C_Sx_u_mod, id.vars = c("unit", "treatment", "timestep"), measure.vars = c("sortie", "field")) # Should be 170 observations
names(SL_L_C_Sx_u_mod2)[names(SL_L_C_Sx_u_mod2) == "variable"] <- "DataSource"
names(SL_L_C_Sx_u_mod2)[names(SL_L_C_Sx_u_mod2) == "value"] <- "C_unit"

SL_L_C_Sx_u_mod2 <- SL_L_C_Sx_u_mod2 %>%
  mutate(unit = as.character(unit))

# Basic linear model
SL_L_C_Sx_lm <- lm(C_unit ~ DataSource, SL_L_C_Sx_u_mod2) # does not force the intercept through zero, tells us the difference between the two means
summary(SL_L_C_Sx_lm)

# Mixed effects models
SL_L_C_Sx_lmer <- lmer(C_unit ~ DataSource * treatment + (1|unit/timestep), SL_L_C_Sx_u_mod2)
summary(SL_L_C_Sx_lmer)

# Plot all timesteps at once

png("./Figures/SL_alltime_L_C_Sx.png", width=700, height=500, units="px", pointsize=23, antialias="default")

ggplot(SL_L_C_Sx_u_mod, aes(x = field, y = sortie, shape = treatment, color = treatment)) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), 
        axis.text = element_text(size = 15), 
        axis.title = element_text(size = 18), 
        legend.title = element_text(size = 18), 
        legend.text = element_text(size = 17)) +
  geom_point(aes(colour = factor(treatment), shape = factor(treatment)), size = 2) +
  geom_abline() +
  scale_x_continuous(breaks = seq(0, 60, by = 10), limits = c(0, 60)) +
  scale_y_continuous(breaks = seq(0, 60, by = 10), limits = c(0, 60)) +
  labs(x = "Observed Carbon (Mg/ha)", y = "Predicted Carbon (Mg/ha)", col = "Treatment", shape = "Treatment") +
  scale_shape_manual(values = c(16, 15, 17),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention"))

dev.off()



### Subalpine fir ###

# Subset for Fir
SL_L_C_Bl <- subset(SL_L_C, SL_L_C$Species == "Bl")

# Recalculate C per unit for spruce only
SL_L_C_Bl <- SL_L_C_Bl %>% 
  dplyr::group_by(timestep, unit) %>% 
  dplyr::mutate(C_unit = sum(C_tree, na.rm = TRUE))

# Select desired columns
SL_L_C_Bl_u <- SL_L_C_Bl %>%
  dplyr::select(unit, timestep, C_unit, treatment)

SL_L_C_Bl_u <- as.data.table(unique(SL_L_C_Bl_u))



### RSS and RMSE ###

# Compare final year of simulation C to final year of field data C - LIVE ONLY
final_SL_L_C_Bl_u <- as.data.table(subset(SL_L_C_Bl_u, timestep == 27))

final_SL_field_L_C_Bl <- subset(SL_field_L_C_Bl, timestep == 27)

final_SL_L_C_Bl_u <- merge(final_SL_L_C_Bl_u, final_SL_field_L_C_Bl, by = c("unit", "treatment", "timestep"))
names(final_SL_L_C_Bl_u)[names(final_SL_L_C_Bl_u) == "C_unit.x"] <- "C_unit"
names(final_SL_L_C_Bl_u)[names(final_SL_L_C_Bl_u) == "C_unit.y"] <- "field_C"

SL_Bl_rss <- with(final_SL_L_C_Bl_u, sum((C_unit - field_C)^2))
SL_Bl_rmse <- with(final_SL_L_C_Bl_u, sqrt(mean((C_unit - field_C)^2)))



### Linear and mixed effects models ###

# Data manipulation
SL_L_C_Bl_u_mod <- subset(SL_L_C_Bl_u, timestep == 0 | timestep ==  2 | timestep == 5 | timestep == 17 | timestep == 27)

SL_L_C_Bl_u_mod <- merge(SL_L_C_Bl_u_mod, SL_field_L_C_Bl, by = c("unit", "treatment", "timestep")) # okay that this data frame has 85 observations instead of 93 - the missing observations are because units 16-19 were not measured in years 2 and 5 

names(SL_L_C_Bl_u_mod)[names(SL_L_C_Bl_u_mod) == "C_unit.x"] <- "sortie"
names(SL_L_C_Bl_u_mod)[names(SL_L_C_Bl_u_mod) == "C_unit.y"] <- "field"

SL_L_C_Bl_u_mod2 <- melt(SL_L_C_Bl_u_mod, id.vars = c("unit", "treatment", "timestep"), measure.vars = c("sortie", "field")) # Should be 170 observations
names(SL_L_C_Bl_u_mod2)[names(SL_L_C_Bl_u_mod2) == "variable"] <- "DataSource"
names(SL_L_C_Bl_u_mod2)[names(SL_L_C_Bl_u_mod2) == "value"] <- "C_unit"

SL_L_C_Bl_u_mod2 <- SL_L_C_Bl_u_mod2 %>%
  mutate(unit = as.character(unit))

# Basic linear model
SL_L_C_Bl_lm <- lm(C_unit ~ DataSource, SL_L_C_Bl_u_mod2) # does not force the intercept through zero, tells us the difference between the two means
summary(SL_L_C_Bl_lm)

# Mixed effects models
SL_L_C_Bl_lmer <- lmer(C_unit ~ DataSource * treatment + (1|unit/timestep), SL_L_C_Bl_u_mod2)
summary(SL_L_C_Bl_lmer)

# Plot all timesteps at once

png("./Figures/SL_alltime_L_C_Bl.png", width=700, height=500, units="px", pointsize=23, antialias="default")

ggplot(SL_L_C_Bl_u_mod, aes(x = field, y = sortie, shape = treatment, color = treatment)) +
  theme_bw() + 
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), 
        axis.text = element_text(size = 15), 
        axis.title = element_text(size = 18), 
        legend.title = element_text(size = 18), 
        legend.text = element_text(size = 17)) +
  geom_point(aes(colour = factor(treatment), shape = factor(treatment)), size = 2) +
  geom_abline() +
  scale_x_continuous(breaks = seq(0, 85, by = 10), limits = c(0, 85)) +
  scale_y_continuous(breaks = seq(0, 85, by = 10), limits = c(0, 85)) +
  labs(x = "Observed Carbon (Mg/ha)", y = "Predicted Carbon (Mg/ha)", col = "Treatment", shape = "Treatment") +
  scale_shape_manual(values = c(16, 15, 17),
                     breaks = c("ctrl", "med", "low"), 
                     labels = c("Control", "Medium retention", "Low retention")) +
  scale_colour_manual(values = c("#F8766D", "#619CFF", "#00BA38"), 
                      breaks = c("ctrl", "med", "low"), 
                      labels = c("Control", "Medium retention", "Low retention"))

dev.off()



##################
### Date Creek ###
##################

### Western redcedar ###

DC_L_C_Cw <- subset(DC_L_C, DC_L_C$Species == "Cw")

# Recalculate C per unit for cedar only
DC_L_C_Cw_p <- DC_L_C_Cw %>% 
  group_by(timestep, Unit, PlotNumber) %>% 
  mutate(C_plot = sum(C_tree, na.rm = TRUE))

# Select desired columns
DC_L_C_Cw_p <- DC_L_C_Cw_p %>% 
  select(timestep, Unit, PlotNumber, C_plot, Treatment, count)

DC_L_C_Cw_p <- unique(DC_L_C_Cw_p)

# Calculate carbon per unit by averaging carbon per plot
DC_L_C_Cw_u <- DC_L_C_Cw_p %>% 
  group_by(timestep, Unit) %>% 
  mutate(C_unit = sum(C_plot, na.rm = TRUE)/count)

# Select desired columns
DC_L_C_Cw_u <- DC_L_C_Cw_u %>% 
  select(timestep, Unit, C_unit, Treatment)

DC_L_C_Cw_u <- unique(DC_L_C_Cw_u)



### Western hemlock ###

DC_L_C_Hw <- subset(DC_L_C, DC_L_C$Species == "Hw")

# Recalculate C per plot for hemlock only
DC_L_C_Hw_p <- DC_L_C_Hw %>% 
  group_by(timestep, Unit, PlotNumber) %>% 
  mutate(C_plot = sum(C_tree, na.rm = TRUE))

# Select desired columns
DC_L_C_Hw_p <- DC_L_C_Hw_p %>% 
  select(timestep, Unit, PlotNumber, C_plot, Treatment, count)

DC_L_C_Hw_p <- unique(DC_L_C_Hw_p)

# Calculate carbon per unit by averaging carbon per plot
DC_L_C_Hw_u <- DC_L_C_Hw_p %>% 
  group_by(timestep, Unit) %>% 
  mutate(C_unit = sum(C_plot, na.rm = TRUE)/count)

# Select desired columns
DC_L_C_Hw_u <- DC_L_C_Hw_u %>% 
  select(timestep, Unit, C_unit, Treatment)

DC_L_C_Hw_u <- unique(DC_L_C_Hw_u)


```



6. Coarse woody debris 
```{r}
###################
### Summit Lake ###
###################



##################
### Date Creek ###
##################




```





